### ISSUE TITLE
Multiple Server Connection Management

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#1415]
## Overview

Save the details for connecting to multiple servers in the client for easy switching.

Prototype: https://invis.io/D370J4DYQ#/151974085_Openbazaar-Connect-Inital-Screen
## Requirements
- [x] As a user, I need to add many server configurations (#1)
- [x] As a user, I need to delete an existing server configuration (#2)
- [x] As a user, I need to edit an existing server configuration (#3)
- [x] As a user, I need to be alerted if/when a server fails to connect (#4)
- [x] As a first time user, I should automatically connect to my local server (#5)
- [x] As a user, I should NOT be able to edit or delete a server I'm already connected to. (#6)
- [x] Activate one of the connections. (#7)
- [x] Automatically save the local connection
- [x]  It should be easy to restore the local (default) connection to the original onboarding state
- [x] The local connection is editable

![0](https://trello-attachments.s3.amazonaws.com/57155d7d9b1e6684501f1f3d/2482x1442/e16f92ffd8d9c3dad48201ec415df2ef/openbazaar-connect-servers-none-connected%402x.png)

**Comment by morebrownies** [comment]
The design should be all set on this, but I may have to spend a bit time touching it up after Rob finishes his work.

**Comment by drwasho** [comment]
## Requirements

- [ ] As a user, I need to add many server configurations (#1)
- [ ] As a user, I need to delete an existing server configuration (#2)
- [ ] As a user, I need to edit an existing server configuration (#3)
- [ ] As a user, I need to be alerted if/when a server fails to connect (#4)
- [ ] As a first time user, I should automatically connect to my local server (#5)
- [ ] As a user, I should NOT be able to edit or delete a server I'm already connected to. (#6)
- [ ] Activate one of the connections. (#7)
- [ ] Automatically save the local connection
- [ ]  It should be easy to restore the local (default) connection to the original onboarding state
- [ ] The local connection is editable

https://trello-attachments.s3.amazonaws.com/57155d7d9b1e6684501f1f3d/2482x1442/e16f92ffd8d9c3dad48201ec415df2ef/openbazaar-connect-servers-none-connected%402x.png

**Comment by rmisio** [comment]
this is done and ready for verification.

**Comment by jjeffryes** [comment]
Verified and complete.

**Comment by Dekker3D** [comment]
I'd like to point out that your "use testnet" setting should probably be per server config, not global, since you'll want it to match your server's testnet setting?

**Comment by jjeffryes** [comment]
Currently, the only way to run in testnet on the server is to manually add a testnet flag on the command line when you start the server, and the server doesn't notify the client when that's the case.

When/if we add the functionality to have the server tell the client when it's in testnet mode, we'll remove the testnet control from the settings.
